### ISSUE TITLE
Feature Requests:

### ISSUE THREAD

**Issue by motionmonster** [motionmonster/Stanimation#1]
- [x] Movable camera

- [x] Layers

Image support

Custom canvas size

Gif export

**Comment by RodneyBaker** [comment]
Looks like Beta 2 has delivered 'Image support' and 'Gif Export'.
Not sure about 'Custom Canvas size'...

Nice work on Beta 2.  Looking very good.

**Comment by motionmonster** [comment]
Custom canvas is in there too.
