### ISSUE TITLE
Drawing new circles have a default tickness which doesn't correspond with the current tickness

### ISSUE THREAD

**Issue by PixelGuy123** [motionmonster/Stanimation#2]
Exactly, if you simply draw a figure and check the tickness, it's for some reason on 10 (which is the max), it should be in 1

**Comment by motionmonster** [comment]
Segments that are created not attached to an existing figure automatically get a thickness of 10.  Stan is built with a thickness of 22.  10 isn't the max.  I might in the future add some settings to the top where you can choose thickness and color before creating segments (like in the pencil tool already).
