### ISSUE TITLE
Frames with some figures using opacity < 255 causes a lot of lag in the editor

### ISSUE THREAD

**Issue by PixelGuy123** [motionmonster/Stanimation#6]
Exactly, if the figure is < 255 (except = 0), it causes a lot of lag depending on the size of the figure (how much does it cover the screen basically) and how many of them

**Comment by motionmonster** [comment]
This is a side effect of the way rendering is done.  The individual segments are not drawn all together, but one at a time.  To make transparency render correctly, the figure is drawn to a framebuffer and then drawn to the screen with opacity applied.

It should perform well with a few figures or maybe 1 complex figure.   If performance is starting to lag, you can go to the view menu and uncheck high quality transparency (shortcut \).  It will still render with the better transparency option.

**Comment by PixelGuy123** [comment]
Oh right, I honestly forgot that option existed, thx!
